using Microsoft.EntityFrameworkCore;


    public class OnyxDBContext : DbContext 
{ 
    public OnyxDBContext(DbContextOptions<OnyxDBContext> options): base(options)
    {
    
    }

    public DbSet<Part> Parts { get; set; }
    public DbSet<YellowPart> YellowParts { get; set; }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Part>().HasData(
            //new Part
            //{
            //    ID = 6821,
            //    OrderNumber = "21009716",
            //    WALLNUM = "0",
            //    ROOMNUM = "1",
            //    LINNUM = "1",
            //    PARTQTY = 1,
            //    WIDTH = 11.5000M,
            //    WIDTHSTR = "11 1/4",
            //    LENGTH = 36.2500M,
            //    LENGTHSTR = "36",
            //    DEPTH = 0.7500M,
            //    DEPTHSTR = "0.5",
            //    PARTID = 8,
            //    PARTNAME = "Unfinished End Left",
            //    MATERIALID = "1867",
            //    MATERIALNAME = "0500 DL LAM / RAW PLY",
            //    MATLISTNUM = "1",
            //    MATGRAINDEF = "NULL",
            //    OPTIMIZE = "NULL",
            //    STOCKPART = "NULL",
            //    WASTEFACTOR = "NULL",
            //    MATCOST = "NULL",
            //    MATCOSTUNIT = "NULL",
            //    LABORMINUTES = "NULL",
            //    MATTYPE = "NULL",
            //    UDF2DEC = "NULL",
            //    UDF3DEC = "NULL",
            //    UDF4DEC = "NULL",
            //    CABNAME = "W-3636BD",
            //    CABNAMETYPE = "W",
            //    PARTCOMMENT = "NULL",
            //    PARTBANDCODE = "NULL",
            //    ROOMNAME = "NULL",
            //    SECONDPRTPROG = "NULL",
            //    PRIMARYPRTPROGMIRR = "NULL",
            //    SECONDPRTPROGMIRR = "NULL",
            //    PPPBARCODE = "NULL",
            //    SPPBARCODE = "NULL",
            //    JOBDESCRIPTION = "NULL",
            //    INTBANDMAT = "NULL",
            //    INTBANDCOLOR = "NULL",
            //    isCNC = true,
            //    isPanelSaw = false,
            //    isShowing = false,
            //    isYellow = false,
            //    DeptID = 2,
            //    UserID = 7777,
            //    Schedule = "SCHEDULE 00-01",
            //}, 
            //new Part
            //{
            //    ID = 6822,
            //    OrderNumber = "21009716",
            //    WALLNUM = "0",
            //    ROOMNUM = "1",
            //    LINNUM = "1",
            //    PARTQTY = 1,
            //    WIDTH = 11.500M,
            //    WIDTHSTR = "11 1/4",
            //    LENGTH = 36.250M,
            //    LENGTHSTR = "36",
            //    DEPTH = 0.750M,
            //    DEPTHSTR = "0.5",
            //    PARTID = 10,
            //    PARTNAME = "Unfinished End Right",
            //    MATERIALID = "1867",
            //    MATERIALNAME = "0500 DL LAM / RAW PLY",
            //    MATLISTNUM = "1",
            //    MATGRAINDEF = "NULL",
            //    OPTIMIZE = "NULL",
            //    STOCKPART = "NULL",
            //    WASTEFACTOR = "NULL",
            //    MATCOST = "NULL",
            //    MATCOSTUNIT = "NULL",
            //    LABORMINUTES = "NULL",
            //    MATTYPE = "NULL",
            //    UDF2DEC = "NULL",
            //    UDF3DEC = "NULL",
            //    UDF4DEC = "NULL",
            //    CABNAME = "W-3636BD",
            //    CABNAMETYPE = "W",
            //    PARTCOMMENT = "NULL",
            //    PARTBANDCODE = "NULL",
            //    ROOMNAME = "NULL",
            //    SECONDPRTPROG = "NULL",
            //    PRIMARYPRTPROGMIRR = "NULL",
            //    SECONDPRTPROGMIRR = "NULL",
            //    PPPBARCODE = "NULL",
            //    SPPBARCODE = "NULL",
            //    JOBDESCRIPTION = "NULL",
            //    INTBANDMAT = "NULL",
            //    INTBANDCOLOR = "NULL",
            //    isCNC = true,
            //    isPanelSaw = true,
            //    isShowing = true,
            //    isNonShow = true,
            //    isYellow = false,
            //    DeptID = 2,
            //    UserID = 7777,
            //    Schedule = "SCHEDULE 00-01",
            //},
            //new Part
            //{
            //    ID = 6823,
            //    OrderNumber = "21009716",
            //    WALLNUM = "0",
            //    ROOMNUM = "1",
            //    LINNUM = "1",
            //    PARTQTY = 1,
            //    WIDTH = 11.7500M,
            //    WIDTHSTR = "11 1/2",
            //    LENGTH = 34.7500M,
            //    LENGTHSTR = "34 1/2",
            //    DEPTH = 0.3750M,
            //    DEPTHSTR = "0.125",
            //    PARTID = 11,
            //    PARTNAME = "Bottom",
            //    MATERIALID = "1839",
            //    MATERIALNAME = "0500 CL BIRCH C3 F2S PLY",
            //    MATLISTNUM = "1",
            //    MATGRAINDEF = "NULL",
            //    OPTIMIZE = "NULL",
            //    STOCKPART = "NULL",
            //    WASTEFACTOR = "NULL",
            //    MATCOST = "NULL",
            //    MATCOSTUNIT = "NULL",
            //    LABORMINUTES = "NULL",
            //    MATTYPE = "NULL",
            //    UDF2DEC = "NULL",
            //    UDF3DEC = "NULL",
            //    UDF4DEC = "NULL",
            //    CABNAME = "W-3636BD",
            //    CABNAMETYPE = "W",
            //    PARTCOMMENT = "NULL",
            //    PARTBANDCODE = "NULL",
            //    ROOMNAME = "NULL",
            //    SECONDPRTPROG = "NULL",
            //    PRIMARYPRTPROGMIRR = "NULL",
            //    SECONDPRTPROGMIRR = "NULL",
            //    PPPBARCODE = "NULL",
            //    SPPBARCODE = "NULL",
            //    JOBDESCRIPTION = "NULL",
            //    INTBANDMAT = "NULL",
            //    INTBANDCOLOR = "NULL",
            //    isCNC = true,
            //    isPanelSaw = true,
            //    isShowing = true,
            //    isNonShow = true,
            //    isYellow = false,
            //    DeptID = 2,
            //    UserID = 7777,
            //    Schedule = "SCHEDULE 00-01",
            //}, 
            //new Part
            //{
            //    ID = 6824,
            //    OrderNumber = "21009716",
            //    WALLNUM = "0",
            //    ROOMNUM = "1",
            //    LINNUM = "1",
            //    PARTQTY = 1,
            //    WIDTH = 35.5000M,
            //    WIDTHSTR = "35 1/4",
            //    LENGTH = 34.6250M,
            //    LENGTHSTR = "34 3/8",
            //    DEPTH = 0.7500M,
            //    DEPTHSTR = "0.5",
            //    PARTID = 13,
            //    PARTNAME = "Unf Back",
            //    MATERIALID = "1867",
            //    MATERIALNAME = "0500 DL LAM / RAW PLY",
            //    MATLISTNUM = "1",
            //    MATGRAINDEF = "NULL",
            //    OPTIMIZE = "NULL",
            //    STOCKPART = "NULL",
            //    WASTEFACTOR = "NULL",
            //    MATCOST = "NULL",
            //    MATCOSTUNIT = "NULL",
            //    LABORMINUTES = "NULL",
            //    MATTYPE = "NULL",
            //    UDF2DEC = "NULL",
            //    UDF3DEC = "NULL",
            //    UDF4DEC = "NULL",
            //    CABNAME = "W-3636BD",
            //    CABNAMETYPE = "W",
            //    PARTCOMMENT = "NULL",
            //    PARTBANDCODE = "NULL",
            //    ROOMNAME = "NULL",
            //    SECONDPRTPROG = "NULL",
            //    PRIMARYPRTPROGMIRR = "NULL",
            //    SECONDPRTPROGMIRR = "NULL",
            //    PPPBARCODE = "NULL",
            //    SPPBARCODE = "NULL",
            //    JOBDESCRIPTION = "NULL",
            //    INTBANDMAT = "NULL",
            //    INTBANDCOLOR = "NULL",
            //    isCNC = true,
            //    isPanelSaw = false,
            //    isShowing = false,
            //    isNonShow = true,
            //    isYellow = false,
            //    DeptID = 2,
            //    UserID = 7777,
            //    Schedule = "SCHEDULE 00-01",
            //},
            new Part
            {
                ID = 6825,
                OrderNumber = "21009716",
                WALLNUM = "0",
                ROOMNUM = "1",
                LINNUM = "1",
                PARTQTY = 2,
                WIDTH = 10.8438M,
                WIDTHSTR = "10 19/32",
                LENGTH = 34.6250M,
                LENGTHSTR = "34 3/8",
                DEPTH = 1.0000M,
                DEPTHSTR = "0.75",
                PARTID = 15,
                PARTNAME = "Adjustable Shelf",
                MATERIALID = "1841",
                MATERIALNAME = "0750 CL BIRCH ADJSH PB",
                MATLISTNUM = "1",
                MATGRAINDEF = "NULL",
                OPTIMIZE = "NULL",
                STOCKPART = "NULL",
                WASTEFACTOR = "NULL",
                MATCOST = "NULL",
                MATCOSTUNIT = "NULL",
                LABORMINUTES = "NULL",
                MATTYPE = "NULL",
                UDF2DEC = "NULL",
                UDF3DEC = "NULL",
                UDF4DEC = "NULL",
                CABNAME = "W-3636BD",
                CABNAMETYPE = "W",
                PARTCOMMENT = "NULL",
                PARTBANDCODE = "NULL",
                ROOMNAME = "NULL",
                SECONDPRTPROG = "NULL",
                PRIMARYPRTPROGMIRR = "NULL",
                SECONDPRTPROGMIRR = "NULL",
                PPPBARCODE = "NULL",
                SPPBARCODE = "NULL",
                JOBDESCRIPTION = "NULL",
                INTBANDMAT = "NULL",
                INTBANDCOLOR = "NULL",
                isCNC = true,
                isPanelSaw = false,
                isShowing = false,
                isNonShow = false,
                isYellow = false,
                DeptID = 2,
                UserID = 7777,
                Schedule = "SCHEDULE 00-01",

            });
    }
}
