// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SWiFT_GNC_Scorecard.Migrations
{
    [DbContext(typeof(OnyxDBContext))]
    partial class OnyxDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Part", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CABNAME")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CABNAMETYPE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DEPTH")
                        .HasColumnType("TEXT");

                    b.Property<string>("DEPTHSTR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeptID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("INTBANDCOLOR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("INTBANDMAT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JOBDESCRIPTION")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LABORMINUTES")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LENGTH")
                        .HasColumnType("TEXT");

                    b.Property<string>("LENGTHSTR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LINNUM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MATCOST")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MATCOSTUNIT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MATERIALID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MATERIALNAME")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MATGRAINDEF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MATLISTNUM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MATTYPE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OPTIMIZE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ORDNUM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PARTBANDCODE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PARTCOMMENT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PARTID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PARTNAME")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PARTQTY")
                        .HasColumnType("TEXT");

                    b.Property<string>("PPPBARCODE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PRIMARYPRTPROGMIRR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ROOMNAME")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ROOMNUM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SECONDPRTPROG")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SECONDPRTPROGMIRR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SPPBARCODE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("STOCKPART")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UDF2DEC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UDF3DEC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UDF4DEC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WALLNUM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WASTEFACTOR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WIDTH")
                        .HasColumnType("TEXT");

                    b.Property<string>("WIDTHSTR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isCNC")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isNonShow")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isPanelSaw")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isShowing")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            ID = 6821,
                            CABNAME = "W-3636BD",
                            CABNAMETYPE = "W",
                            DEPTH = 0.7500m,
                            DEPTHSTR = "0.5",
                            DeptID = 0,
                            INTBANDCOLOR = "NULL",
                            INTBANDMAT = "NULL",
                            JOBDESCRIPTION = "NULL",
                            LABORMINUTES = "NULL",
                            LENGTH = 36.2500m,
                            LENGTHSTR = "36",
                            LINNUM = "1",
                            MATCOST = "NULL",
                            MATCOSTUNIT = "NULL",
                            MATERIALID = "1867",
                            MATERIALNAME = "0500 DL LAM / RAW PLY",
                            MATGRAINDEF = "NULL",
                            MATLISTNUM = "1",
                            MATTYPE = "NULL",
                            OPTIMIZE = "NULL",
                            ORDNUM = "21009716",
                            PARTBANDCODE = "NULL",
                            PARTCOMMENT = "NULL",
                            PARTID = 8,
                            PARTNAME = "Unfinished End Left",
                            PARTQTY = 1m,
                            PPPBARCODE = "NULL",
                            PRIMARYPRTPROGMIRR = "NULL",
                            ROOMNAME = "NULL",
                            ROOMNUM = "1",
                            SECONDPRTPROG = "NULL",
                            SECONDPRTPROGMIRR = "NULL",
                            SPPBARCODE = "NULL",
                            STOCKPART = "NULL",
                            UDF2DEC = "NULL",
                            UDF3DEC = "NULL",
                            UDF4DEC = "NULL",
                            WALLNUM = "0",
                            WASTEFACTOR = "NULL",
                            WIDTH = 11.5000m,
                            WIDTHSTR = "11 1/4",
                            isCNC = true,
                            isNonShow = false,
                            isPanelSaw = false,
                            isShowing = false
                        },
                        new
                        {
                            ID = 6822,
                            CABNAME = "W-3636BD",
                            CABNAMETYPE = "W",
                            DEPTH = 0.750m,
                            DEPTHSTR = "0.5",
                            DeptID = 0,
                            INTBANDCOLOR = "NULL",
                            INTBANDMAT = "NULL",
                            JOBDESCRIPTION = "NULL",
                            LABORMINUTES = "NULL",
                            LENGTH = 36.250m,
                            LENGTHSTR = "36",
                            LINNUM = "1",
                            MATCOST = "NULL",
                            MATCOSTUNIT = "NULL",
                            MATERIALID = "1867",
                            MATERIALNAME = "0500 DL LAM / RAW PLY",
                            MATGRAINDEF = "NULL",
                            MATLISTNUM = "1",
                            MATTYPE = "NULL",
                            OPTIMIZE = "NULL",
                            ORDNUM = "21009716",
                            PARTBANDCODE = "NULL",
                            PARTCOMMENT = "NULL",
                            PARTID = 10,
                            PARTNAME = "Unfinished End Right",
                            PARTQTY = 1m,
                            PPPBARCODE = "NULL",
                            PRIMARYPRTPROGMIRR = "NULL",
                            ROOMNAME = "NULL",
                            ROOMNUM = "1",
                            SECONDPRTPROG = "NULL",
                            SECONDPRTPROGMIRR = "NULL",
                            SPPBARCODE = "NULL",
                            STOCKPART = "NULL",
                            UDF2DEC = "NULL",
                            UDF3DEC = "NULL",
                            UDF4DEC = "NULL",
                            WALLNUM = "0",
                            WASTEFACTOR = "NULL",
                            WIDTH = 11.500m,
                            WIDTHSTR = "11 1/4",
                            isCNC = true,
                            isNonShow = true,
                            isPanelSaw = true,
                            isShowing = true
                        },
                        new
                        {
                            ID = 6823,
                            CABNAME = "W-3636BD",
                            CABNAMETYPE = "W",
                            DEPTH = 0.3750m,
                            DEPTHSTR = "0.125",
                            DeptID = 0,
                            INTBANDCOLOR = "NULL",
                            INTBANDMAT = "NULL",
                            JOBDESCRIPTION = "NULL",
                            LABORMINUTES = "NULL",
                            LENGTH = 34.7500m,
                            LENGTHSTR = "34 1/2",
                            LINNUM = "1",
                            MATCOST = "NULL",
                            MATCOSTUNIT = "NULL",
                            MATERIALID = "1839",
                            MATERIALNAME = "0500 CL BIRCH C3 F2S PLY",
                            MATGRAINDEF = "NULL",
                            MATLISTNUM = "1",
                            MATTYPE = "NULL",
                            OPTIMIZE = "NULL",
                            ORDNUM = "21009716",
                            PARTBANDCODE = "NULL",
                            PARTCOMMENT = "NULL",
                            PARTID = 11,
                            PARTNAME = "Bottom",
                            PARTQTY = 1m,
                            PPPBARCODE = "NULL",
                            PRIMARYPRTPROGMIRR = "NULL",
                            ROOMNAME = "NULL",
                            ROOMNUM = "1",
                            SECONDPRTPROG = "NULL",
                            SECONDPRTPROGMIRR = "NULL",
                            SPPBARCODE = "NULL",
                            STOCKPART = "NULL",
                            UDF2DEC = "NULL",
                            UDF3DEC = "NULL",
                            UDF4DEC = "NULL",
                            WALLNUM = "0",
                            WASTEFACTOR = "NULL",
                            WIDTH = 11.7500m,
                            WIDTHSTR = "11 1/2",
                            isCNC = true,
                            isNonShow = true,
                            isPanelSaw = true,
                            isShowing = true
                        },
                        new
                        {
                            ID = 6824,
                            CABNAME = "W-3636BD",
                            CABNAMETYPE = "W",
                            DEPTH = 0.7500m,
                            DEPTHSTR = "0.5",
                            DeptID = 0,
                            INTBANDCOLOR = "NULL",
                            INTBANDMAT = "NULL",
                            JOBDESCRIPTION = "NULL",
                            LABORMINUTES = "NULL",
                            LENGTH = 34.6250m,
                            LENGTHSTR = "34 3/8",
                            LINNUM = "1",
                            MATCOST = "NULL",
                            MATCOSTUNIT = "NULL",
                            MATERIALID = "1867",
                            MATERIALNAME = "0500 DL LAM / RAW PLY",
                            MATGRAINDEF = "NULL",
                            MATLISTNUM = "1",
                            MATTYPE = "NULL",
                            OPTIMIZE = "NULL",
                            ORDNUM = "21009716",
                            PARTBANDCODE = "NULL",
                            PARTCOMMENT = "NULL",
                            PARTID = 13,
                            PARTNAME = "Unf Back",
                            PARTQTY = 1m,
                            PPPBARCODE = "NULL",
                            PRIMARYPRTPROGMIRR = "NULL",
                            ROOMNAME = "NULL",
                            ROOMNUM = "1",
                            SECONDPRTPROG = "NULL",
                            SECONDPRTPROGMIRR = "NULL",
                            SPPBARCODE = "NULL",
                            STOCKPART = "NULL",
                            UDF2DEC = "NULL",
                            UDF3DEC = "NULL",
                            UDF4DEC = "NULL",
                            WALLNUM = "0",
                            WASTEFACTOR = "NULL",
                            WIDTH = 35.5000m,
                            WIDTHSTR = "35 1/4",
                            isCNC = true,
                            isNonShow = true,
                            isPanelSaw = false,
                            isShowing = false
                        },
                        new
                        {
                            ID = 6825,
                            CABNAME = "W-3636BD",
                            CABNAMETYPE = "W",
                            DEPTH = 1.0000m,
                            DEPTHSTR = "0.75",
                            DeptID = 0,
                            INTBANDCOLOR = "NULL",
                            INTBANDMAT = "NULL",
                            JOBDESCRIPTION = "NULL",
                            LABORMINUTES = "NULL",
                            LENGTH = 34.6250m,
                            LENGTHSTR = "34 3/8",
                            LINNUM = "1",
                            MATCOST = "NULL",
                            MATCOSTUNIT = "NULL",
                            MATERIALID = "1841",
                            MATERIALNAME = "0750 CL BIRCH ADJSH PB",
                            MATGRAINDEF = "NULL",
                            MATLISTNUM = "1",
                            MATTYPE = "NULL",
                            OPTIMIZE = "NULL",
                            ORDNUM = "21009716",
                            PARTBANDCODE = "NULL",
                            PARTCOMMENT = "NULL",
                            PARTID = 15,
                            PARTNAME = "Adjustable Shelf",
                            PARTQTY = 2m,
                            PPPBARCODE = "NULL",
                            PRIMARYPRTPROGMIRR = "NULL",
                            ROOMNAME = "NULL",
                            ROOMNUM = "1",
                            SECONDPRTPROG = "NULL",
                            SECONDPRTPROGMIRR = "NULL",
                            SPPBARCODE = "NULL",
                            STOCKPART = "NULL",
                            UDF2DEC = "NULL",
                            UDF3DEC = "NULL",
                            UDF4DEC = "NULL",
                            WALLNUM = "0",
                            WASTEFACTOR = "NULL",
                            WIDTH = 10.8438m,
                            WIDTHSTR = "10 19/32",
                            isCNC = true,
                            isNonShow = false,
                            isPanelSaw = false,
                            isShowing = false
                        });
                });

            modelBuilder.Entity("TrackedTimes", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeptID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("completedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("PartID");

                    b.ToTable("TrackedTimes");
                });

            modelBuilder.Entity("TrackedTimes", b =>
                {
                    b.HasOne("Part", null)
                        .WithMany("trackedTimes")
                        .HasForeignKey("PartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Part", b =>
                {
                    b.Navigation("trackedTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
